# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj''
    feedsToUse: config
    nugetConfigPath: NuGet.config    # Relative to root of the repository
    externalFeedCredentials: <Name of the NuGet service connection>

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true

# ...
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'nic-test - Azure'
    appType: 'webApp'
    WebAppName: 'nic-test'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
